font_family JetBrainsMono Nerd Font
font_size 14
cursor_trail 1
window_padding_width 5 7
window_margin_width 5 7
background_opacity 0.8
background_blur 1

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
